#!/bin/bash
# 20-configure-apt
#
# This script configure apt
#

info " Starting: Configure APT "

#
# Setup the sources.list file for new installations of Debian GNU/Linux.
#

# disable apt sources.list base
sed -i 's/^deb/#deb/' /etc/apt/sources.list

# erase all .list repositories
rm -f /etc/apt/sources.list.d/*.list

# generate new repositories
if [ "$REPO_TYPE" == "local" ]; then
	mirror="file://$REPO_URL/ubuntu/"
else
	mirror="http://$REPO_URL/ubuntu/"
fi

# oficial repositories
cat <<E_O_APT > /etc/apt/sources.list.d/$SUITE.list
# oficial
deb $mirror $SUITE $REPO_SECTIONS
E_O_APT

# PPA repositories
if [ "$ENABLE_PPA" == "yes" ]; then
cat <<E_O_APT > /etc/apt/sources.list.d/ppa.list
# PPA
#PPA elementary-tweaks
deb http://ppa.launchpad.net/mpstark/elementary-tweaks-daily/ubuntu $SUITE main 
deb-src http://ppa.launchpad.net/mpstark/elementary-tweaks-daily/ubuntu $SUITE main 

#PPA Indicadores de Unity
deb http://ppa.launchpad.net/indicator-brightness/ppa/ubuntu $SUITE main 
deb-src http://ppa.launchpad.net/indicator-brightness/ppa/ubuntu $SUITE main

#PPA Install Multimedia Codecs and Enable DVD Playback
deb http://ppa.launchpad.net/mc3man/trusty-media/ubuntu trusty main 
deb-src http://ppa.launchpad.net/mc3man/trusty-media/ubuntu trusty main 

#PPA Java
deb http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu $SUITE main 
deb-src http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu $SUITE main 

#PPA Indicator Synapse
deb http://ppa.launchpad.net/elementary-os/stable/ubuntu $SUITE main 
deb-src http://ppa.launchpad.net/elementary-os/stable/ubuntu $SUITE main 

#PPA For Laptop : Install TLP for Improve Battery Life and Reduce Overheating
deb http://ppa.launchpad.net/linrunner/tlp/ubuntu $SUITE main 
deb-src http://ppa.launchpad.net/linrunner/tlp/ubuntu $SUITE main 

E_O_APT
fi


# backport repositories
if [ "$ENABLE_DOCKER" == "yes" ]; then
apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D 
cat <<E_O_APT > /etc/apt/sources.list.d/dockerproject.list
deb https://apt.dockerproject.org/repo ubuntu-trusty main
E_O_APT
fi

# backport repositories
if [ "$ENABLE_BACKPORTS" == "yes" ]; then
cat <<E_O_APT > /etc/apt/sources.list.d/backports.list
deb $mirror $SUITE-backports $REPO_SECTIONS
E_O_APT
fi

if [ "$ENABLE_REMOTE" == "yes" ]; then
# security and update repositories
cat <<E_O_APT > /etc/apt/sources.list.d/remote.list
# oficial
deb http://$REMOTE_REPO/ubuntu/ $SUITE $REPO_SECTIONS
# updates
deb http://$REMOTE_REPO/ubuntu/ $SUITE-updates $REPO_SECTIONS 
E_O_APT
# lowest priority to remote repository
cat <<EOF > /etc/apt/preferences.d/remote.pref
Package: *
Pin: origin $REMOTE_REPO
Pin-Priority: 100
EOF
fi

if [ "$APT_UPDATES" == "yes" ]; then
# security and update repositories
cat <<E_O_APT > /etc/apt/sources.list.d/updates.list
# updates
deb $mirror $SUITE-updates $REPO_SECTIONS
E_O_APT
fi

if [ "$APT_SECURITY" == "yes" ]; then
# security and update repositories
cat <<E_O_APT > /etc/apt/sources.list.d/security.list
# security
deb http://security.ubuntu.com/ $SUITE-security $REPO_SECTIONS
E_O_APT
fi

cat <<EOF > /etc/apt/apt.conf.d/80-update
Acquire::Check-Valid-Until "false";
EOF

cat <<EOF > /etc/apt/apt.conf.d/10-Ubuntu
Acquire::Language "none";
Acquire::PDiffs  "false";
APT::Install-Recommends  "false";
APT::Get::AutomaticRemove  "true";
APT::Clean-Installed  "true";
EOF

cat <<EOF > /etc/apt/preferences.d/$SUITE.pref
Package: *
Pin: origin ""
Pin-Priority: 1001
    
Package: *
Pin: release n=$SUITE
Pin-Priority: 300

Package: *
Pin: release n=$SUITE-backports
Pin-Priority: 250
EOF$APT -y install 

Debug "Activate i386 architecture"

dpkg --add-architecture i386
$APT -y install binutils-multiarch libstdc++6:i386 libgcc1:i386 zlib1g:i386 libncurses5:i386 libcanberra-pulse:i386 libldap-2.4-2:i386 libpulse0:i386 libxml2:i386 libpng3:i386

debug "Updating APT database"
$APT -y update

#
#  Now that the sources have been setup make sure the system is up to date.
#
# install keyring list ####
debug "Installing Debian/Ubuntu Keyrings"
$APT -y install $KEYRINGS


# upgrade system
debug "Upgrading System"
$APT -y --force-yes install apt
$APT -y upgrade
$APT -y --force-yes install aptitude
