#!/bin/bash
# 02-sysvinit
#
# This script remove systemd and install sysvinit
#

info " Install Graphics Card & utilities "


# remove xserver-xorg-video-nouveau
if [ -n "`dpkg -l | grep -i 'xserver-xorg-video-nouveau'`" ]; then
    $APT remove --purge --auto-remove xserver-xorg-video-nouveau 
fi

# remove xserver-xorg-video-intel
if [ -n "`dpkg -l | grep -i 'xserver-xorg-video-intel'`" ]; then
    $APT remove --purge --auto-remove xserver-xorg-video-intel
fi

# update apt database
$APT -y update

if [ ! -z "`dpkg -l | grep -i 'bumblebee-nvidia'`" ]; then

  # install the nvidia and primus libs and drivers packages
  $APT -y install bumblebee-nvidia primus primus-libs:i386 xserver-xorg-video-intel libtxc-dxtn-s2tc0 libtxc-dxtn-s2tc-bin libtxc-dxtn-s2tc0:i386 nvidia-cg-toolkit mesa-utils mesa-utils-extra libegl1-mesa libegl1-mesa-drivers libgl1-mesa-dri libglapi-mesa libgles1-mesa libgles2-mesa libglu1-mesa libopenvg1-mesa mesa-vdpau-drivers libtxc-dxtn-s2tc0 libtxc-dxtn-s2tc-bin uuid-runtime libegl1-mesa:i386 libegl1-mesa-drivers:i386 libgl1-mesa-dri:i386 libglapi-mesa:i386 libgles1-mesa:i386 libgles2-mesa:i386 libglu1-mesa:i386 libopenvg1-mesa:i386 mesa-vdpau-drivers:i386 libtxc-dxtn-s2tc0:i386

WARN=$(cat << _MSG
 ---------- [ Removing legacy Drivers Nvidia /Intel ] ---------------

  we are removing graphics drivers legacy from this system, 
  we need to restart for apply changes.

  please restart the installation when complete.
  
 ------------------------------------------------
_MSG
)
echo "$WARN"

reboot

fi


debug "Nvidia Optimus Graphics Cards was installed on this system!"